### ISSUE TITLE
500 Internal Server Error caused when classes are entered wrong

### ISSUE THREAD

**Issue by vicnl75** [s-moffatt/selectives3#10]
500 Internal Server Error caused when classes are entered wrong, Step 2: Register doesn't load for students. Make it more user-friendly.

Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/views.py", line 190, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
  File "/srv/views.py", line 1099, in get
    jdata = cls.GetJdata(institution, session, auth)
  File "/srv/views.py", line 755, in ScheduleGetJdata
    c['hover_text'] = logic.GetHoverText(institution, session, use_full_description, c)
  File "/srv/logic.py", line 37, in GetHoverText
    class_desc += '\nMax Enrollment: ' + str(c['max_enrollment'])
KeyError: 'max_enrollment'

**Comment by vicnl75** [comment]
Maybe to give a better error message instead of internal server error.
