### ISSUE TITLE
View attendance & View by Homeroom: 500 Internal Error

### ISSUE THREAD

**Issue by vicnl75** [s-moffatt/selectives3#31]

**Comment by vicnl75** [comment]
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/views.py", line 190, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
  File "/srv/reports.py", line 910, in get
    data = cls.GetReport(institution, session, auth)
  File "/srv/reports.py", line 382, in GetViewAttendance
    classes_to_display.sort(key=alphaOrder)
TypeError: '<' not supported between instances of 'str' and 'tuple'

----------------
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/views.py", line 190, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
  File "/srv/reports.py", line 910, in get
    data = cls.GetReport(institution, session, auth)
  File "/srv/reports.py", line 442, in GetViewByHomeroom
    classes_by_homeroom[room] = getClassesByHomeroom(
  File "/srv/reports.py", line 417, in getClassesByHomeroom
    classes_to_display.sort(key=alphaOrder)
TypeError: '<' not supported between instances of 'str' and 'tuple'

Both seems to be related to the alphaOrder function returning inconsistent datatype for sorting ('str' vs 'tuple')
